### ISSUE TITLE
Curl returning empty string

### ISSUE THREAD

**Issue by codehimanshu** [GDG-JSS-NOIDA/tech_blog#2]
I want to get data from facebook like button.
`www.fecebook.com/plugins/like.php?href=http%3A%2F%2Fwww.google.com`
But the curl response gives an empty string output on var_dump.

**Comment by codehimanshu** [comment]
Refer [link to file](https://github.com/GDG-JSS-NOIDA/tech_blog/blob/master/resources/views/leaderboard.blade.php)

**Comment by MilindaLaknath** [comment]
Hi @codehimanshu 

I will handle it

Thank you

**Comment by neomax22** [comment]
<?php
$ch = curl_init();
$url= 'https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.google.com';
$timeout = 5;
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$browser = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36';
curl_setopt($ch, CURLOPT_USERAGENT, $browser);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
$data = curl_exec($ch);
curl_close($ch);
var_dump($data);
?>

**Comment by neomax22** [comment]
```php
<?php
$ch = curl_init();
$url= 'https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.google.com';
$timeout = 5;
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$browser = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36';
curl_setopt($ch, CURLOPT_USERAGENT, $browser);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
$data = curl_exec($ch);
curl_close($ch);
var_dump($data);
?>
```

**Comment by shivangg** [comment]
You seem to misspell `facebook` as `fecebook`
